language: python
python:
  - 3.6
install:
  - make init
env:
  global:
    COVERALLS_REPO_TOKEN:
      secure: imj4NqTInySL9FDKflm/2LS6OIOYIOw0HhyHwIt2AnphJttwRdSw+XWuZFUf1oTnLoAQzO+ZYpaSvL6dbkMofEKTchyg2UJXsmdkdNwucOSqcGPaceiE1itZk5Hj8xmxdwsrRyYjYJ5UXG1H7rAzaTWvEHsu1YXrhHm8mI4Dgqs1xyBZN2wrU6+P8ekatc4rPaMu+jo319apPexMFLQaTwJ7/HWJDfmDF9onAEH0qj8TA1mFo9qQbNLyyhhxsz2zsL4jO2X5Ohbg4XUBqneV4AWZ/NEtZB2s8LvD7HniXdS1D2+Ry1xeAu4mkbAm8LRFc9Kf4i1tOLnJzq4B6BqjRctiVaCSlVOGqfFjK+fK4QsU8gemdbSlxm8rxAxL80Sj9vT/XbleABvZvDv8W07bS76ICTc++5S7NxGu5CbHtsZG3Z5FKOp2aCqZudCnagOO/5aOnLVFuhWDKBRTtUZOuaHtQE3W/y08EjWuNUbAmWHUBq1JJXGoS1heBpVC+UjSvDYQeaU8zeGkpo9NmNJIYu5N1P6VQXHo0dCN++La1/g8VjFAEfRgUaLYlhWWzDVQdZAHKNYIwayc6aDx+ntTHKhZqmYKfhLFawrzGYmHk/yFAiPbh42pmsAmE3T2MlRBgF3/c8FCql2k3erxzSxFJAaafCfcglCpzT9nk1ToiJU=

jobs:
  include:
    - script:
        - make test
      after_script:
        - coveralls
    - script:
        - make dist
      sudo: required
      services:
        - docker
